In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
sns.set_style("whitegrid")

In [4]:
users = pd.read_csv(r"C:\Users\kuldiep\Downloads\Data\users.csv")
events = pd.read_csv(r"C:\Users\kuldiep\Downloads\Data\events.csv")
orders = pd.read_csv(r"C:\Users\kuldiep\Downloads\Data\orders.csv")

In [5]:
print(users.shape)
print(events.shape)
print(orders.shape)

(150000, 5)
(404931, 3)
(28909, 4)

In [6]:
users.head()

   user_id signup_date    country  device       channel
0        1  2025-06-02    Germany  Tablet    Google Ads
1        2  2025-09-20  Australia  Mobile       Organic
2        3  2025-01-01         UK  Mobile         Email
3        4  2025-04-21      India  Mobile      Referral
4        5  2025-02-23     Canada  Mobile  Facebook Ads

In [7]:
events.head()

   user_id        event   timestamp
0        1        visit  2025-05-30
1        1       signup  2025-06-02
2        1     activate  2025-06-03
3        1  add_to_cart  2025-06-04
4        2        visit  2025-09-15

In [8]:
orders.head()

   order_id  user_id  order_value  order_date
0         1        3       715.24  2025-01-03
1         2        9      2163.04  2025-05-27
2         3       28      4187.43  2025-01-19
3         4       33      3411.03  2025-12-17
4         5       34      1372.67  2025-07-14

In [9]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   user_id      150000 non-null  int64
 1   signup_date  150000 non-null  object
 2   country      150000 non-null  object
 3   device       150000 non-null  object
 4   channel      150000 non-null  object
dtypes: int64(1), object(4)
memory usage: 5.7+ MB

In [10]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404931 entries, 0 to 404930
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    404931 non-null  int64
 1   event      404931 non-null  object
 2   timestamp  404931 non-null  object
dtypes: int64(1), object(2)
memory usage: 9.3+ MB

In [11]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28909 entries, 0 to 28908
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     28909 non-null  int64
 1   user_id      28909 non-null  int64
 2   order_value  28909 non-null  float64
 3   order_date   28909 non-null  object
dtypes: float64(1), int64(2), object(1)
memory usage: 903.5+ KB

In [14]:
#Checking for Nulls
print(users.isnull().sum())
print(events.isnull().sum())
print(orders.isnull().sum())

user_id        0
signup_date    0
country        0
device         0
channel        0
dtype: int64
user_id      0
event        0
timestamp    0
dtype: int64
order_id       0
user_id        0
order_value    0
order_date     0
dtype: int64

In [15]:
# Checking fot Duplicates
print(users.duplicated().sum())
print(events.duplicated().sum())
print(orders.duplicated().sum())

0
0
0

In [16]:
print(users["country"].value_counts())
print(users["device"].value_counts())
print(users["channel"].value_counts())
print(events["event"].value_counts())

country
Canada       21622
Germany      21570
Australia    21506
UAE          21470
USA          21367
UK           21338
India        21127
Name: count, dtype: int64
device
Mobile     104935
Desktop     37538
Tablet       7527
Name: count, dtype: int64
channel
Email           25172
Google Ads      25150
Facebook Ads    24959
Affiliate       24925
Organic         24898
Referral        24896
Name: count, dtype: int64
event
visit          150000
signup         112650
activate        73225
add_to_cart     40147
purchase        28909
Name: count, dtype: int64

In [17]:
print(orders["order_value"].describe())

count    28909.000000
mean      2577.415053
std       1395.866820
min        150.350000
25%       1383.500000
50%       2585.100000
75%       3773.980000
max       4999.710000
Name: order_value, dtype: float64